name: Docker image build

on: 
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push
        run: |
          docker login --username marek38 --password ${{ secrets.TOKEN }} ghcr.io
          docker build . --tag ghcr.io/marek38/test:latest 
          docker push ghcr.io/marek38/test:latest